# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Troop 423
email: Troop423Webmaster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Troop 423's website. This webpage is still in development.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://troop423.github.io" # the base hostname & protocol for your site
gems:
  - jekyll-feed
# Build settings
markdown: kramdown
